routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Storage;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\admin\AdminController;
use App\Http\Controllers\admin\SupplierController;
use App\Http\Controllers\admin\CustomerController;
use App\Http\Controllers\admin\CategoryController;
use App\Http\Controllers\admin\BrandController;
use App\Http\Controllers\admin\ProductController;
use App\Http\Controllers\admin\UserManageController;






/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => 'auth'], function () {

    Route::get('/', [HomeController::class, 'index'])->name('home_route');

    Route::get('/admin-dashboard', [AdminController::class, 'index'])->name('admin.dashboard');

        Route::resource('manage-user', UserManageController::class);

        Route::resource('supplier', SupplierController::class);

        Route::resource('customer', CustomerController::class);

        Route::resource('category', CategoryController::class);

        Route::resource('brand', BrandController::class);

        Route::resource('product', ProductController::class);

    });

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $fillable = [
        'category_id', 'brand_id','product_name', 'price', 'image'
    ];

    public function category(){
        return $this->belongsTo(Category::class);
    }

    public function brand(){
        return $this->belongsTo(Brand::class);
    }
}

app/Http/Controllers/admin/ProductController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;

use App\Models\Product;

use App\Models\Category;

use App\Models\Brand;

use DataTables;

use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        if ($request->ajax()) {

            $data = Product::with('category', 'brand')->orderBy('id', 'desc')->get();

            return Datatables::of($data)

                ->addIndexColumn()

                ->addColumn('image', function ($row) {
                    return '<img src="' . asset('dashboard/product/' . $row->image) . '" width="50%" height="50%" class="img-fluid">';
                })

                ->addColumn('categorys', function ($row) {
                    return optional($row->category)->category_name;
                })

                ->addColumn('brands', function ($row) {
                    return optional($row->brand)->brand_name;
                })

                ->addColumn('action', function ($row) {
                    return '<a href="' . route('product.edit', $row->id) . '" class="edit btn btn-primary btn-sm">Edit</a>';
                })

                ->rawColumns(['image', 'categorys', 'brands', 'action'])

                ->make(true);
        }
        return view('dashboard.product.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['category'] = Category::get();

        $data['brand'] = Brand::get();

        return view('dashboard.product.create', compact('data'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
            'category_id' => ['required'],
            'brand_id' => ['required'],
            'product_name' => ['required'],
            'price' => ['required'],
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg,webp|max:2048',
        ]);

        // Get the file from the request
        $image = $request->file('image');

        // Generate a unique name for the file to avoid conflicts
        $filename = time() . '.' . $image->getClientOriginalExtension();

        // Save the image to the public folder
        $image->move('dashboard/product/', $filename);


        Product::create([
            'category_id' => $request->category_id,
            'brand_id' => $request->brand_id,
            'product_name' => $request->product_name,
            'price' => $request->price,
            'image' => $filename,
            'stock_alert_qty' => $request->stock_alert_qty,
        ]);

        return redirect()->route('product.index')->with('success', 'Product has been created successfully.');
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $data['product'] = Product::find($id);

        $data['category'] = Category::get();

        $data['brand'] = Brand::get();

        return view('dashboard.Product.edit', compact('data'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $product = Product::find($id);

        $request->validate([
            'category_id' => ['required'],
            'brand_id' => ['required'],
            'product_name' => ['required'],
            'price' => ['required'],
            'image' => 'image|mimes:jpeg,png,jpg,gif,svg,webp|max:2048',
        ]);

        if ($request->hasFile('image')) {
            // Get the file from the request
            $image = $request->file('image');

            // Generate a unique name for the file to avoid conflicts
            $filename = time() . '.' . $image->getClientOriginalExtension();

            // Save the image to the public folder
            $image->move('dashboard/product/', $filename);
        } else {
            $filename = $product->image;
        }


        Product::find($id)->update([
            'category_id' => $request->category_id,
            'brand_id' => $request->brand_id,
            'product_name' => $request->product_name,
            'price' => $request->price,
            'image' => $filename,
            'stock_alert_qty' => $request->stock_alert_qty,
        ]);

        return redirect()->route('product.index')->with('success', 'Product has been updated successfully');
    }
}

resources/views/dashboard/product/create.blade.php
@extends('layouts.app')
@section('title')
    Create Product
@endsection
@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0"></h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Create Product</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <section class="content">
            <div class="container-fluid">
                <div class="card">
                    <div class="row">
                        <div class="col-md-3"></div>
                        <div class="col-md-6">
                            <h4 class="mt-3 mb-3">Create Product</h4>
                            <form method="POST" action="{{ route('product.store') }}" enctype="multipart/form-data">
                                @csrf

                                <div class="row mb-3">
                                    <label for="name"
                                        class="col-md-4 col-form-label text-md-end">{{ __('Product Name') }} <span
                                            style="color:red">*</span></label>

                                    <div class="col-md-6">
                                        <input id="name" type="text"
                                            class="form-control @error('product_name') is-invalid @enderror"
                                            name="product_name" value="{{ old('product_name') }}" required
                                            autocomplete="name" autofocus>

                                        @error('product_name')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <label for="password-confirm"
                                        class="col-md-4 col-form-label text-md-end">{{ __('Select Category') }} <span
                                            style="color:red">*</span></label>

                                    <div class="col-md-6">
                                        <select class="form-control" name="category_id" required>
                                            <option value="">Select Category </option>
                                            @foreach ($data['category'] as $categorys)
                                                <option value="{{ $categorys->id }}">{{ $categorys->category_name }}
                                                </option>
                                            @endforeach
                                        </select>
                                        @error('category_id')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <label for="password-confirm"
                                        class="col-md-4 col-form-label text-md-end">{{ __('Select Brand') }} <span
                                            style="color:red">*</span></label>

                                    <div class="col-md-6">
                                        <select class="form-control" name="brand_id" required>
                                            <option value="">Select Brand </option>
                                            @foreach ($data['brand'] as $brands)
                                                <option value="{{ $brands->id }}">{{ $brands->brand_name }}</option>
                                            @endforeach
                                        </select>
                                        @error('brand_id')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <label for="name"
                                        class="col-md-4 col-form-label text-md-end">{{ __('Product Price') }} <span
                                            style="color:red">*</span></label>

                                    <div class="col-md-6">
                                        <input id="name" type="number"
                                            class="form-control @error('price') is-invalid @enderror" name="price"
                                            value="{{ old('price') }}" required autocomplete="name" autofocus>

                                        @error('price')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <label for="name"
                                        class="col-md-4 col-form-label text-md-end">{{ __('Stock Alert Quantity') }} <span
                                            style="color:red">*</span></label>

                                    <div class="col-md-6">
                                        <input id="name" type="number"
                                            class="form-control @error('stock_alert_qty') is-invalid @enderror"
                                            name="stock_alert_qty" value="{{ old('stock_alert_qty') }}" required
                                            autocomplete="name" autofocus>

                                        @error('stock_alert_qty')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <label for="name"
                                        class="col-md-4 col-form-label text-md-end">{{ __('Product Image') }} <span
                                            style="color:red">*</span></label>

                                    <div class="col-md-6">
                                        <input id="name" type="file"
                                            class="form-control @error('image') is-invalid @enderror" name="image"
                                            required autocomplete="name" autofocus>

                                        @error('image')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>



                                <div class="row mb-3 mt-3">
                                    <div class="col-md-6 offset-md-4">
                                        <button type="submit" class="btn btn-primary">
                                            {{ __('Submit') }}
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="col-md-3"></div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/dashboard/product/edit.blade.php
@extends('layouts.app')
@section('title')
    Create Product
@endsection
@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0"></h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Create Product</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <section class="content">
            <div class="container-fluid">
                <div class="card">
                    <div class="row">
                        <div class="col-md-3"></div>
                        <div class="col-md-6">
                            <h4 class="mt-3 mb-3">Update Product</h4>
                            <form method="POST" action="{{ route('product.update',$data['product']->id) }}" enctype="multipart/form-data">
                                @csrf
                                {{method_field('PATCH')}}
                                <div class="row mb-3">
                                    <label for="name"
                                        class="col-md-4 col-form-label text-md-end">{{ __('Product Name') }} <span
                                            style="color:red">*</span></label>

                                    <div class="col-md-6">
                                        <input id="name" type="text"
                                            class="form-control @error('product_name') is-invalid @enderror"
                                            name="product_name" value="{{ $data['product']->product_name }}" required
                                            autocomplete="name" autofocus>

                                        @error('product_name')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <label for="password-confirm"
                                        class="col-md-4 col-form-label text-md-end">{{ __('Select Category') }} <span
                                            style="color:red">*</span></label>

                                    <div class="col-md-6">
                                        <select class="form-control" name="category_id" required>
                                            <option value="">Select Category </option>
                                            @foreach ($data['category'] as $categorys)
                                                <option value="{{ $categorys->id }}" @if($categorys->id==$data['product']->category_id) selected @endif>{{ $categorys->category_name }}
                                                </option>
                                            @endforeach
                                        </select>
                                        @error('category_id')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <label for="password-confirm"
                                        class="col-md-4 col-form-label text-md-end">{{ __('Select Brand') }} <span
                                            style="color:red">*</span></label>

                                    <div class="col-md-6">
                                        <select class="form-control" name="brand_id" required>
                                            <option value="">Select Brand </option>
                                            @foreach ($data['brand'] as $brands)
                                                <option value="{{ $brands->id }}" @if($brands->id==$data['product']->brand_id) selected @endif>{{ $brands->brand_name }}</option>
                                            @endforeach
                                        </select>
                                        @error('brand_id')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <label for="name"
                                        class="col-md-4 col-form-label text-md-end">{{ __('Product Price') }} <span
                                            style="color:red">*</span></label>

                                    <div class="col-md-6">
                                        <input id="name" type="number"
                                            class="form-control @error('price') is-invalid @enderror" name="price"
                                            value="{{ $data['product']->price }}" required autocomplete="name" autofocus>

                                        @error('price')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <label for="name"
                                        class="col-md-4 col-form-label text-md-end">{{ __('Stock Alert Quantity') }} <span
                                            style="color:red">*</span></label>

                                    <div class="col-md-6">
                                        <input id="name" type="number"
                                            class="form-control @error('stock_alert_qty') is-invalid @enderror"
                                            name="stock_alert_qty" value="{{ $data['product']->stock_alert_qty }}" required
                                            autocomplete="name" autofocus>

                                        @error('stock_alert_qty')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <label for="name"
                                        class="col-md-4 col-form-label text-md-end">{{ __('Product Image') }} <span
                                            style="color:red">*</span></label>

                                    <div class="col-md-6">
                                        <input id="name" type="file"
                                            class="form-control @error('image') is-invalid @enderror" name="image"
                                             autocomplete="name" autofocus>
                                            <br>
                                            <img width="100px" height="100px" src="{{ asset('dashboard/product/'.$data['product']->image) }}">
                                        @error('image')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>



                                <div class="row mb-3 mt-3">
                                    <div class="col-md-6 offset-md-4">
                                        <button type="submit" class="btn btn-primary">
                                            {{ __('Submit') }}
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="col-md-3"></div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/dashboard/product/index.blade.php
@extends('layouts.app')
@section('title') Product @endsection
@section('content')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0"></h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Product List</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>

    <section class="content">
      <div class="container-fluid">
         <table class="table table-bordered data-table">
                <thead>
                    <tr>
                        <th>Sl</th>
                        <th>Name</th>
                        <th>Category</th>
                        <th>Brand</th>
                        <th>Price</th>
                        <th>Image</th>
                        <th width="100px">Action</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
      </div>
    </section>
  </div>

  @section('script')

  <script>
    $(document).ready(function() {
               $('.data-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('product.index') }}",
                columns: [
                    {
                    data: 'DT_RowIndex',
                    name: 'DT_RowIndex',
                },
                {data: 'product_name', name: 'product_name'},
                {data: 'categorys', name: 'categorys'},
                {data: 'brands', name: 'brands'},
                {data: 'price', name: 'price'},
                {data: 'image', name: 'image'},
                {data: 'action', name: 'action', orderable: false, searchable: false},
                ]
            });
        });
  </script>
  @endsection
@endsection